### ISSUE TITLE
Example usage will only work once

### ISSUE THREAD

**Issue by zeke** [actions/npm#1]
The example workflow in the README _does_ work, but it will only work once, as the same version number cannot be published more than once. It would be useful to provide an example workflow that would work for continually (or conditionally) publishing new updates, or at least set expectations about the existing example in the README.

**Comment by bcoe** [comment]
@nickvanw @zeke I've been working on a workflow that automatically tags, generates a CHANGELOG, and publishes an npm module:

https://github.com/conventional-commits/conventional-commits-action

based on [conventional commits](https://www.conventionalcommits.org/en/v1.0.0-beta.2/).

Would love feedback, and help fleshing this out further.

**Comment by hbetts** [comment]
@nickvanw my understanding of the GitHub-provided filter is that the filter only filters on the `tag` event. Therefore, there's no way to create an Action that _could_ generate a tag, and then filter prior to the publish Action to ensure that the publish Action is only called if a tag was created in the prior Action.

If we were to publish in the same workflow as the Action that _may_ create a tag, then we would need to develop a filter that just verifies that the previous Action created a new tag.

**Comment by swinton** [comment]
> we've recommended adding a filter before publish that will only publish when a `tag` is created

Reflecting this recommendation in #4.
