### ISSUE TITLE
NPM / Node.js Version Support

### ISSUE THREAD

**Issue by mpareja** [actions/npm#12]
It looks like the Docker image is based on Node 10. Have you considered the need for running `npm test` under different versions of node?

(I don't actually have access to Actions beta (:crossed_fingers:), so it is entirely possible I'm missing something obvious here.)

**Comment by mcolyer** [comment]
Our current plan is to support a single version of node for our npm Action. However we definitely recognize the need to test multiple versions of node. Once you gain access to actions it would be great to have you create actions for the other versions you're interested in supporting.

**Comment by kdawgwilk** [comment]
I am currently hitting this issue firebase/firebase-functions#437 which currently has a workaround to use node 8 but I am unable to do so because this action I am using doesn't support different node versions 😢
