### ISSUE TITLE
CERT_UNTRUSTED

### ISSUE THREAD

**Issue by yellowstonebum** [actions/npm#15]
Hi there, I got a CERT_UNTRUSTED message and was wondering if there was a work around.

npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)

Thanks!

**Comment by hfaulds** [comment]
Hello @yellowstonebum,
Can you give any more information about what caused this error, what are the `uses` and `args` of the action and, if applicable, the contents of the `package.json` you're using?

**Comment by iamwilhelm** [comment]
It's likely you're using an old version of npm that came packaged with an old version of node. I mistakenly used v0.10.14 rather than v10.14.0, and got this sort of error.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
