### ISSUE TITLE
need auth

### ISSUE THREAD

**Issue by o-t-w** [actions/npm#17]
I am seeing this error in my log: 

> npm ERR! need auth auth required for publishing
> npm ERR! need auth You need to authorize this machine using `npm adduser`

I have created a token on npmjs.com.
My main.workflow file: 
```
workflow "New workflow" {
  on = "push"
  resolves = ["Publish"]
}

action "Publish" {
  args = "publish --access public"
  uses = "actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437"
  runs = "npm publish"
  secrets = ["NPM_AUTH_TOKEN"]
}
```

I tried adding an adduser command 
```

action "GitHub Action for npm" {
  uses = "actions/npm@e7aaefed7c9f2e83d493ff810f17fa5ccd7ed437"
  runs = "npm adduser"
  secrets = ["NPM_AUTH_TOKEN"]
}
```
but that still errored :(

It would be nice to have clearer documentation :)

**Comment by mcolyer** [comment]
@o-t-w did you add the secret to your repository via https://github.com/o-t-w/YOURREPONAME/settings/secrets?

> It would be nice to have clearer documentation :)

Definitely, once we figure out what's up - we'll try to make it more clear.

**Comment by o-t-w** [comment]
I created the secret using the action GUI 
<img width="892" alt="screen shot 2019-01-11 at 10 15 17" src="https://user-images.githubusercontent.com/29547922/51027871-e187ff80-1589-11e9-9dda-e980d80f8908.png">

**Comment by mcolyer** [comment]
Try removing the `runs = "npm publish"` from your workflow file.

**Comment by o-t-w** [comment]
I removed `runs = "npm publish"`
I now get the error `You do not have permission to publish "button". Are you logged in as the correct user? : button`

**Comment by hfaulds** [comment]
@o-t-w 
> Edit: I managed to get this to work.
Do you mind if I close this issue?

If you have any feedback on how we could make this issue easier to avoid that would be really appreciated 😄

**Comment by fearphage** [comment]
> Edit: I managed to get this to work.

It would be nice/convenient to post your solution here in case others run into it.

**Comment by thepwagner** [comment]
Closing as solved+stale.
