### ISSUE TITLE
Using the npm action not from the root directory

### ISSUE THREAD

**Issue by paulvollmer** [actions/npm#22]
hello,

i've a project with multiple `package.json`  files.
each `package.json` is inside a directory at the root dir.

i looked at the code at this repo to figure out if it is possible to set the directory for the action, but i could not find anything.

an env var could set the target directory. something like that:

```
action "Build" {
  uses = "actions/npm@master"
  args = "install"
  env = {
    DIR = "./path/to/package"
  }
}
```

**Comment by zackify** [comment]
I'm wanting to do the same thing

**Comment by zackify** [comment]
@paulvollmer I figured out an easy way to do this. 

Edit your action. change it to my fork: zackify/npm@354aa07c3dc1f17f66afa69d1ddaac4620dc0668

now you can cd before :)

![image](https://user-images.githubusercontent.com/449136/52324592-bf21b000-2996-11e9-8975-b09ce1eb76b2.png)

**Comment by paulvollmer** [comment]
okay, thank you for the fast reply. i will use your fork.

**Comment by jonatanalava** [comment]
mine fails with your fork `Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"cd\": executable file not found in $PATH": unknown` I must be doing something wrong

**Comment by zackify** [comment]
@jonatanalava did you point your action to use my fork?

**Comment by jonatanalava** [comment]
Yes. I'm using `zackify/npm@354aa07c3dc1f17f66afa69d1ddaac4620dc0668`

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
