### ISSUE TITLE
install from private github repository

### ISSUE THREAD

**Issue by paulvollmer** [actions/npm#25]
is there a way to install a npm package from a private github repository?
i could imagine something with the `GITHUB_TOKEN` env var.

on my local machine it is not a problem with the ssh key or the github api token but i had no chance to use the same solution inside the docker container.

any ideas?

**Comment by shawnrushefsky** [comment]
I am also having this issue.

**Comment by paulvollmer** [comment]
A `Deployment Key` could also be a solution to install private packages.
i found [this](https://circleci.com/docs/2.0/gh-bb-integration/#deployment-keys-and-user-keys) at the  circle ci docs.
And [here](https://gist.github.com/eschwartz/8518b21d5d2854d8a4f7c7e7507f0561) is a gist about adding a ssh key to a docker container. I'm not sure what's the best solution. a ssh key or github token to install. like...
```
"dependencies": {
"GitRepo": "git+https://<token-from-github>:x-oauth-basic@github.com/<user>/<GitRepo>.git"
}
```

**Comment by mcolyer** [comment]
> And [here](https://gist.github.com/eschwartz/8518b21d5d2854d8a4f7c7e7507f0561) is a gist about adding a ssh key to a docker container. I'm not sure what's the best solution. a ssh key or github token to install. like...

I was going to suggest something similar. A GitHub token is probably slightly preferable as it has more limited access.

**Comment by paulvollmer** [comment]
i tried the github token way like the following, but npm will not use the env var.
i run a test to check if the GITHUB_TOKEN can clone but if i `git clone` i get the following error

```
fatal: could not read Password for 'https://[FILTERED]@github.com/<user>/<repo>.git': No such device or address
```

**Comment by shawnrushefsky** [comment]
I ended up making my own Dockerfile to handle this.

I modeled the Dockerfile after [this](https://gist.github.com/eschwartz/8518b21d5d2854d8a4f7c7e7507f0561)

I made it so you can pass your ssh keys in with secrets, based on [this](https://github.com/maddox/actions/tree/master/ssh)

I would share my solution directly, but it's in a private repo

**Comment by thepwagner** [comment]
I think a deployment key(s) on the repository that hosts the module is the best solution here - https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys
The `GITHUB_TOKEN` provided by the Action is scoped to the repository that's hosting the Workflow - it won't have access to the repo containing the private module.
A personal access token (`OAuth tokens` in the above link) would work, but affords more privileges than the Action needs (the Action only needs read-only access to specific repos).

The NPM action could support deployment keys better:
- [ ] inject a https://git-scm.com/docs/api-credentials#_credential_helpers to return a deployment key from a secret (i.e. for `github.com/user/repo.git` return `DEPLOYKEY_GITHUB_USER_REPO` secret if it exists)
- [ ] bake in `github.com`'s ssh pubkey to discourage `StrictHostKeyChecking=no`


Things get easier if you setup a https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users  - there's only key so the NPM action could just `ssh-agent && ssh-add` that key before invoking NPM.

The single-key setup would also work with deployment keys, as long as there's only a single private module to install. The credential helper is only required for least-privilege / maximum tinfoil when there's >1 private module to install.

**Comment by fearphage** [comment]
I took the [base npm `entrypoint.sh`](https://github.com/actions/npm/blob/59b64a598378f31e49cb76f27d6f3312b582f680/entrypoint.sh) and added a few lines to get install working from a private npm repo:

```shell
if [ -n "$DEPLOY_KEY" ]; then
  mkdir -p /root/.ssh

  ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts

  echo "$DEPLOY_KEY" > /root/.ssh/id_rsa

  chmod 400 /root/.ssh/id_rsa
fi
```

You can see the complete file and usage instructions below:

https://gist.github.com/fearphage/ef6949a10ddd828a649a0488b7f9bf20

This should get you up and running. It's not the best solution, but it is a solution.

**Comment by mpdude** [comment]
Does this help?

https://github.com/marketplace/actions/webfactory-ssh-agent

**Comment by hfaulds** [comment]
CC @andymckay @chrispat 
I think we need consistent and coherent guidance as this is a comment use-case.
Something like https://github.com/marketplace/actions/webfactory-ssh-agent seems awesome and potentially something we should suggest.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
