### ISSUE TITLE
Failed to install in Ubuntu.

### ISSUE THREAD

**Issue by analtrivedi** [actions/npm#26]
I am trying to install Angular cli using below command. But unfortunately failed every time..
Command;
npm install -g @angular/cli 

Error Log..
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/lib/nodejs/node-v10.15.1-linux-x64/bin/node',
1 verbose cli   '/usr/local/lib/nodejs/node-v10.15.1-linux-x64/bin/npm',
1 verbose cli   'install',
1 verbose cli   '-g',
1 verbose cli   '@angular/cli' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session c2825d996948a9c2
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData error for @angular/cli@latest request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 140316365121408:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
8 timing stage:rollbackFailedOptional Completed in 1ms
9 timing stage:runTopLevelLifecycles Completed in 119ms
10 verbose type system
11 verbose stack FetchError: request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 140316365121408:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:
11 verbose stack
11 verbose stack     at ClientRequest.req.on.err (/usr/local/lib/nodejs/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/node-fetch-npm/src/index.js:68:14)
11 verbose stack     at ClientRequest.emit (events.js:189:13)
11 verbose stack     at onerror (/usr/local/lib/nodejs/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/agent-base/index.js:100:9)
11 verbose stack     at callbackError (/usr/local/lib/nodejs/node-v10.15.1-linux-x64/lib/node_modules/npm/node_modules/agent-base/index.js:122:5)
11 verbose stack     at process._tickCallback (internal/process/next_tick.js:68:7)
12 verbose cwd /home/CORPUSERS/XXXXXX
13 verbose Linux 4.4.0-142-generic
14 verbose argv "/usr/local/lib/nodejs/node-v10.15.1-linux-x64/bin/node" "/usr/local/lib/nodejs/node-v10.15.1-linux-x64/bin/npm" "install" "-g" "@angular/cli"
15 verbose node v10.15.1
16 verbose npm  v6.4.1
17 error code EPROTO
18 error errno EPROTO
**19 error request to https://registry.npmjs.org/@angular%2fcli failed, reason: write EPROTO 140316365121408:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:../deps/openssl/openssl/ssl/record/ssl3_record.c:252:**
20 verbose exit [ 1, true ]

Please suggest me how to solve this issue...

**Comment by thepwagner** [comment]
Hey @analtrivedi 
That error doesn't seem related to this project - which is intended to wrap NPM for execution in [GitHub Actions](https://github.com/features/actions) .

Googling for `npm install "routines:ssl3_get_record:wrong version"` provides a bunch of things you may find helpful - it may be a proxy on your network? Good luck!
