### ISSUE TITLE
Running prepare or prepublishOnly script to create files before publish fails `cannot run in wd`

### ISSUE THREAD

**Issue by alex-page** [actions/npm#27]
I was hoping to run a prepare npm script to minify some files before running `npm publish`.  You can view the actions I was trying here:
https://github.com/alex-page/harmonograph/runs/67959262

Running prepare would fail with the following error 
```
npm WARN lifecycle harmonograph@2.0.2~prepare: cannot run in wd harmonograph@2.0.2 npm run build (wd=.)
```

The scripts failing in the `package.json` are:
```json
{
  "prepare": "npm run build",
  "build": "uglifyjs harmonograph.js --compress --mangle --output ./harmonograph.min.js",
}
```

From my understanding it cannot run `npm run build` in the working directory.  Doing this locally works, I might not understand the restrictions of GitHub actions correctly. 

If I was to create a seperate action for `npm run build` it works so there is nothing special with permissions going on.

**Comment by mcolyer** [comment]
@alex-page if you set [unsafe-perm](https://docs.npmjs.com/misc/config#unsafe-perm) to `true`, does it work? Actions runs as root and I think that's why it might be failing.

**Comment by alex-page** [comment]
@mcolyer I can check that. I have not tested it as I didn't feel comfortable doing that.

**Comment by wangzuo** [comment]
I think for now it may be better to throw an error when the prepare scrips fail.

**Comment by alex-page** [comment]
@mcolyer I had some time to check it out now, sorry for the late reply. `--unsafe-perm` does work when added to the workflow:
```
action "Publish" {
  uses = "actions/npm@master"
  args = "publish --access public --unsafe-perm"
  needs = ["Install dependencies"]
  secrets = ["NPM_AUTH_TOKEN"]
}
```

I am going to close this issue as the problem is related to running the npm action as the `root` user. 

I still found this a little confusing as a user and assumed this would work by default. I will create a pull request for the readme file to add some minor documentation.
