### ISSUE TITLE
Access to NPX

### ISSUE THREAD

**Issue by fearphage** [actions/npm#30]
Could we get an [npx](https://medium.com/@maybekatz/introducing-npx-an-npm-package-runner-55f7d4bd282b) action? It only needs a one character change from the current npm entrypoint.sh (`npm` -> `npx`). This would allow executing things without installing them... like [pkg](https://github.com/zeit/pkg) for instance.

**Comment by zeke** [comment]
I wonder if `docker://node:alpine` includes `npx` 🤔 

See https://jasonet.co/posts/use-github-actions-for-ci/

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
