### ISSUE TITLE
Npm Issue Code 0 Error

### ISSUE THREAD

**Issue by Kashyab19** [actions/npm#32]
![Screenshot from 2019-07-17 21:30:54](https://user-images.githubusercontent.com/22251972/61391416-47a76380-a8da-11e9-83eb-9abffb519e5b.png)

I have installed Yarn and Curl and NPM too.Still I get this error!
Help me out!

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
