### ISSUE TITLE
npm access tokens have same 2fa requirements as user

### ISSUE THREAD

**Issue by kumavis** [actions/npm#33]
Seems I'm unable to create an access token that doesn't need my 2FA OTP codes.

This restriction is not mentioned in the documentation.

**Comment by mikecousins** [comment]
Yup, this sucks.

**Comment by hfaulds** [comment]
This appears to be a limitation with npm, not with this specific action:
- https://github.com/npm/npm/issues/19131
- https://npm.community/t/publish-on-ci-with-2fa/534
Unfortunately I don't think there's anything we can do here.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
