### ISSUE TITLE
npm -install -g yo error 

### ISSUE THREAD

**Issue by jmvd70** [actions/npm#35]
when i type "npm install -g yo" it try to install the package, but after a few seconds, it throws a "Error: SSL Error: CERT_UNTRUSTED", with visual studio 2017 enterprise.

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
