### ISSUE TITLE
HCL vs YAML?

### ISSUE THREAD

**Issue by AndrewLane** [actions/npm#36]
Should the example be migrated to YAML?  I'm still learning, but it looks like the HCL syntax is being sunset?

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
