### ISSUE TITLE
error install laravel mix

### ISSUE THREAD

**Issue by jssvalagua** [actions/npm#37]
jesus@jesus-pc:/var/www/netaday$ npm i
npm http GET https://registry.npmjs.org/axios
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/cross-env
npm http GET https://registry.npmjs.org/laravel-mix
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/popper.js
npm http GET https://registry.npmjs.org/resolve-url-loader
npm http GET https://registry.npmjs.org/sass
npm http GET https://registry.npmjs.org/sass-loader
npm http GET https://registry.npmjs.org/vue
npm http GET https://registry.npmjs.org/axios
npm http GET https://registry.npmjs.org/cross-env
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/laravel-mix
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/sass
npm http GET https://registry.npmjs.org/popper.js
npm http GET https://registry.npmjs.org/sass-loader
npm http GET https://registry.npmjs.org/resolve-url-loader
npm http GET https://registry.npmjs.org/vue
npm http GET https://registry.npmjs.org/axios
npm http GET https://registry.npmjs.org/cross-env
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/laravel-mix
npm http GET https://registry.npmjs.org/bootstrap
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/sass
npm http GET https://registry.npmjs.org/sass-loader
npm http GET https://registry.npmjs.org/popper.js
npm http GET https://registry.npmjs.org/resolve-url-loader
npm ERR! Error: CERT_UNTRUSTED
npm ERR!     at SecurePair.<anonymous> (tls.js:1370:32)
npm ERR!     at SecurePair.EventEmitter.emit (events.js:92:17)
npm ERR!     at SecurePair.maybeInitFinished (tls.js:982:10)
npm ERR!     at CleartextStream.read [as _read] (tls.js:469:13)
npm ERR!     at CleartextStream.Readable.read (_stream_readable.js:320:10)
npm ERR!     at EncryptedStream.write [as _write] (tls.js:366:25)
npm ERR!     at doWrite (_stream_writable.js:223:10)
npm ERR!     at writeOrBuffer (_stream_writable.js:213:5)
npm ERR!     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
npm ERR!     at write (_stream_readable.js:583:24)
npm ERR!     at flow (_stream_readable.js:592:7)
npm ERR!     at Socket.pipeOnReadable (_stream_readable.js:624:5)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-148-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "i"
npm ERR! cwd /var/www/netaday
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm http GET https://registry.npmjs.org/vue
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/netaday/npm-debug.log
npm ERR! not ok code 0
jesus@jesus-pc:/var/www/netaday$

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
