### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by Noeky** [actions/npm#40]
When I'm trying to deploy the solution from https://github.com/SharePoint/sp-dev-fx-webparts/tree/master/samples/react-script-editor

I'm getting the following error when I run npm install 
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (C:\Users\..\AppData\Roaming\nvm\v0.10.0\node_modules\npm\lib\cache.js:671:24) npm ERR!     at C:\Users\..\AppData\Roaming\nvm\v0.10.0\node_modules\npm\lib\cache.js:597:10
npm ERR!     at saved (C:\Users\..\AppData\Roaming\nvm\v0.10.0\node_modules\npm\node_modules\npm-registry-client\lib\get.js:138:7)
npm ERR!     at Object.oncomplete (fs.js:93:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Windows_NT 6.2.9200
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd ..\react-script-editor
npm ERR! node -v v0.10.0
npm ERR! npm -v 1.2.14
npm ERR! type called_on_non_object

I'm running the node version of the project with nvm. Any suggestion on how to fix this error?

**Comment by chrispat** [comment]
# Important

This action is deprecated in favor of using the [`run`](https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstepsrun) script step in the new YAML language to run the various cli tools represented by these actions. 

For feature requests and feedback please head over to the community forum. https://github.community/t5/GitHub-Actions/bd-p/actions
