### ISSUE TITLE
Error: ENOENT, stat 'angular/cli'

### ISSUE THREAD

**Issue by MasterAmw** [actions/npm#6]
npm WARN `git config --get remote.origin.url` returned wrong result (git://github.com/angular/cli) 
npm WARN `git config --get remote.origin.url` returned wrong result (git@github.com:angular/cli) 
npm ERR! addLocal Could not install angular/cli
npm ERR! Error: ENOENT, stat 'angular/cli'
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 3.13.0-162-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "@angular/cli"
npm ERR! cwd /home/amila/Workspace/sbos_clock
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! path angular/cli
npm ERR! code ENOENT
npm ERR! errno 34
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/amila/Workspace/sbos_clock/npm-debug.log
npm ERR! not ok code 0

I got this error response when try to install angular/cli

**Comment by byCedric** [comment]
I'm not an expert, but I think there might be something wrong with your node/npm version. I'm pretty sure that is not node version 10... Did you use the GitHub Actions workflow, or just used npm from cli? If you have used GitHub actions, can you share a bit more how you set it up? If not, I would recommend you to [update your node to not-use an end of life version](https://github.com/nodejs/Release) or open an issue in the [npm community](https://npm.community/).

**Comment by mcolyer** [comment]
> If not, I would recommend you to [update your node to not-use an end of life version](https://github.com/nodejs/Release) or open an issue in the [npm community](https://npm.community/).

Closing this out as I believe this isn't directly related to GitHub Actions.
